// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com5vnetwork.tm_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class TunConfig (
  val name: String,
  val mtu: Long,
  val cidr4: CIDR? = null,
  val cidr6: CIDR? = null,
  val dnsServers4: List<String>? = null,
  val dnsServers6: List<String>? = null,
  val ipv4Routes: List<CIDR>? = null,
  val ipv6Routes: List<CIDR>? = null,
  val whileListApps: List<String>? = null,
  val blackListApps: List<String>? = null,
  val redirectStdErr: Boolean,
  val enableIPv6: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TunConfig {
      val name = pigeonVar_list[0] as String
      val mtu = pigeonVar_list[1] as Long
      val cidr4 = pigeonVar_list[2] as CIDR?
      val cidr6 = pigeonVar_list[3] as CIDR?
      val dnsServers4 = pigeonVar_list[4] as List<String>?
      val dnsServers6 = pigeonVar_list[5] as List<String>?
      val ipv4Routes = pigeonVar_list[6] as List<CIDR>?
      val ipv6Routes = pigeonVar_list[7] as List<CIDR>?
      val whileListApps = pigeonVar_list[8] as List<String>?
      val blackListApps = pigeonVar_list[9] as List<String>?
      val redirectStdErr = pigeonVar_list[10] as Boolean
      val enableIPv6 = pigeonVar_list[11] as Boolean
      return TunConfig(name, mtu, cidr4, cidr6, dnsServers4, dnsServers6, ipv4Routes, ipv6Routes, whileListApps, blackListApps, redirectStdErr, enableIPv6)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      mtu,
      cidr4,
      cidr6,
      dnsServers4,
      dnsServers6,
      ipv4Routes,
      ipv6Routes,
      whileListApps,
      blackListApps,
      redirectStdErr,
      enableIPv6,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CIDR (
  val address: String,
  val prefixLength: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CIDR {
      val address = pigeonVar_list[0] as String
      val prefixLength = pigeonVar_list[1] as Long
      return CIDR(address, prefixLength)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      prefixLength,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TunConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CIDR.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TunConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CIDR -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TmAndroidApi {
  fun prepare(callback: (Result<Boolean>) -> Unit)
  fun start(config: ByteArray, tunConfig: TunConfig, callback: (Result<Unit>) -> Unit)
  fun stop()
  fun getStatus(): Long
  fun config(): ByteArray

  companion object {
    /** The codec used by TmAndroidApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `TmAndroidApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TmAndroidApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tm_android.TmAndroidApi.prepare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.prepare{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tm_android.TmAndroidApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ByteArray
            val tunConfigArg = args[1] as TunConfig
            api.start(configArg, tunConfigArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tm_android.TmAndroidApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tm_android.TmAndroidApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStatus())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tm_android.TmAndroidApi.config$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.config())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
