// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct TunnelConfig {
  var mtu: Int64? = nil
  var dnsServers4: [String]? = nil
  var dnsServers6: [String]? = nil
  var ipv4Addresses: [String]? = nil
  var ipv4SubnetMasks: [String]? = nil
  var ipv4IncludedRoutes: [Ipv4Route]? = nil
  var ipv4ExcludedRoutes: [Ipv4Route]? = nil
  var ipv6Addresses: [String]? = nil
  var ipv6NetworkPrefixLengths: [Int64]? = nil
  var ipv6IncludedRoutes: [Ipv6Route]? = nil
  var ipv6ExcludedRoutes: [Ipv6Route]? = nil
  var useFd: Bool
  var log: Bool
  var tun46Setting: Int64? = nil
  var defaultNicSupport6: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TunnelConfig? {
    let mtu: Int64? = nilOrValue(pigeonVar_list[0])
    let dnsServers4: [String]? = nilOrValue(pigeonVar_list[1])
    let dnsServers6: [String]? = nilOrValue(pigeonVar_list[2])
    let ipv4Addresses: [String]? = nilOrValue(pigeonVar_list[3])
    let ipv4SubnetMasks: [String]? = nilOrValue(pigeonVar_list[4])
    let ipv4IncludedRoutes: [Ipv4Route]? = nilOrValue(pigeonVar_list[5])
    let ipv4ExcludedRoutes: [Ipv4Route]? = nilOrValue(pigeonVar_list[6])
    let ipv6Addresses: [String]? = nilOrValue(pigeonVar_list[7])
    let ipv6NetworkPrefixLengths: [Int64]? = nilOrValue(pigeonVar_list[8])
    let ipv6IncludedRoutes: [Ipv6Route]? = nilOrValue(pigeonVar_list[9])
    let ipv6ExcludedRoutes: [Ipv6Route]? = nilOrValue(pigeonVar_list[10])
    let useFd = pigeonVar_list[11] as! Bool
    let log = pigeonVar_list[12] as! Bool
    let tun46Setting: Int64? = nilOrValue(pigeonVar_list[13])
    let defaultNicSupport6: Bool? = nilOrValue(pigeonVar_list[14])

    return TunnelConfig(
      mtu: mtu,
      dnsServers4: dnsServers4,
      dnsServers6: dnsServers6,
      ipv4Addresses: ipv4Addresses,
      ipv4SubnetMasks: ipv4SubnetMasks,
      ipv4IncludedRoutes: ipv4IncludedRoutes,
      ipv4ExcludedRoutes: ipv4ExcludedRoutes,
      ipv6Addresses: ipv6Addresses,
      ipv6NetworkPrefixLengths: ipv6NetworkPrefixLengths,
      ipv6IncludedRoutes: ipv6IncludedRoutes,
      ipv6ExcludedRoutes: ipv6ExcludedRoutes,
      useFd: useFd,
      log: log,
      tun46Setting: tun46Setting,
      defaultNicSupport6: defaultNicSupport6
    )
  }
  func toList() -> [Any?] {
    return [
      mtu,
      dnsServers4,
      dnsServers6,
      ipv4Addresses,
      ipv4SubnetMasks,
      ipv4IncludedRoutes,
      ipv4ExcludedRoutes,
      ipv6Addresses,
      ipv6NetworkPrefixLengths,
      ipv6IncludedRoutes,
      ipv6ExcludedRoutes,
      useFd,
      log,
      tun46Setting,
      defaultNicSupport6,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Ipv4Route {
  var address: String
  var subnetMask: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Ipv4Route? {
    let address = pigeonVar_list[0] as! String
    let subnetMask = pigeonVar_list[1] as! String

    return Ipv4Route(
      address: address,
      subnetMask: subnetMask
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      subnetMask,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Ipv6Route {
  var address: String
  var networkPrefixLength: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Ipv6Route? {
    let address = pigeonVar_list[0] as! String
    let networkPrefixLength = pigeonVar_list[1] as! Int64

    return Ipv6Route(
      address: address,
      networkPrefixLength: networkPrefixLength
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      networkPrefixLength,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return TunnelConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return Ipv4Route.fromList(self.readValue() as! [Any?])
    case 131:
      return Ipv6Route.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TunnelConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? Ipv4Route {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? Ipv6Route {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol XIosApi {
  func getStatus() throws -> Int64
  func start(config: FlutterStandardTypedData, tunnelConfig: TunnelConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func stop() throws
  func config() throws -> FlutterStandardTypedData
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class XIosApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `XIosApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: XIosApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tm_ios.XIosApi.getStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStatusChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tm_ios.XIosApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! FlutterStandardTypedData
        let tunnelConfigArg = args[1] as! TunnelConfig
        api.start(config: configArg, tunnelConfig: tunnelConfigArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tm_ios.XIosApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let configChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tm_ios.XIosApi.config\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configChannel.setMessageHandler { _, reply in
        do {
          let result = try api.config()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configChannel.setMessageHandler(nil)
    }
  }
}
