// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class TunConfig {
  TunConfig({
    required this.name,
    required this.mtu,
    this.cidr4,
    this.cidr6,
    this.dnsServers4,
    this.dnsServers6,
    this.ipv4Routes,
    this.ipv6Routes,
    this.whileListApps,
    this.blackListApps,
    this.redirectStdErr = true,
    this.enableIPv6 = true,
  });

  String name;

  int mtu;

  CIDR? cidr4;

  CIDR? cidr6;

  List<String>? dnsServers4;

  List<String>? dnsServers6;

  List<CIDR>? ipv4Routes;

  List<CIDR>? ipv6Routes;

  List<String>? whileListApps;

  List<String>? blackListApps;

  bool redirectStdErr;

  bool enableIPv6;

  Object encode() {
    return <Object?>[
      name,
      mtu,
      cidr4,
      cidr6,
      dnsServers4,
      dnsServers6,
      ipv4Routes,
      ipv6Routes,
      whileListApps,
      blackListApps,
      redirectStdErr,
      enableIPv6,
    ];
  }

  static TunConfig decode(Object result) {
    result as List<Object?>;
    return TunConfig(
      name: result[0]! as String,
      mtu: result[1]! as int,
      cidr4: result[2] as CIDR?,
      cidr6: result[3] as CIDR?,
      dnsServers4: (result[4] as List<Object?>?)?.cast<String>(),
      dnsServers6: (result[5] as List<Object?>?)?.cast<String>(),
      ipv4Routes: (result[6] as List<Object?>?)?.cast<CIDR>(),
      ipv6Routes: (result[7] as List<Object?>?)?.cast<CIDR>(),
      whileListApps: (result[8] as List<Object?>?)?.cast<String>(),
      blackListApps: (result[9] as List<Object?>?)?.cast<String>(),
      redirectStdErr: result[10]! as bool,
      enableIPv6: result[11]! as bool,
    );
  }
}

class CIDR {
  CIDR({
    required this.address,
    required this.prefixLength,
  });

  String address;

  int prefixLength;

  Object encode() {
    return <Object?>[
      address,
      prefixLength,
    ];
  }

  static CIDR decode(Object result) {
    result as List<Object?>;
    return CIDR(
      address: result[0]! as String,
      prefixLength: result[1]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TunConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is CIDR) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return TunConfig.decode(readValue(buffer)!);
      case 130: 
        return CIDR.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TmAndroidApi {
  /// Constructor for [TmAndroidApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TmAndroidApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> prepare() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_android.TmAndroidApi.prepare$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> start(Uint8List config, TunConfig tunConfig) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_android.TmAndroidApi.start$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config, tunConfig]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stop() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_android.TmAndroidApi.stop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> getStatus() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_android.TmAndroidApi.getStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<Uint8List> config() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_android.TmAndroidApi.config$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Uint8List?)!;
    }
  }
}
