// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class TunnelConfig {
  TunnelConfig({
    this.mtu,
    this.dnsServers4,
    this.dnsServers6,
    this.ipv4Addresses,
    this.ipv4SubnetMasks,
    this.ipv4IncludedRoutes,
    this.ipv4ExcludedRoutes,
    this.ipv6Addresses,
    this.ipv6NetworkPrefixLengths,
    this.ipv6IncludedRoutes,
    this.ipv6ExcludedRoutes,
    this.useFd = false,
    this.log = false,
    this.tun46Setting,
    this.defaultNicSupport6,
  });

  int? mtu;

  List<String>? dnsServers4;

  List<String>? dnsServers6;

  List<String>? ipv4Addresses;

  List<String>? ipv4SubnetMasks;

  List<Ipv4Route>? ipv4IncludedRoutes;

  List<Ipv4Route>? ipv4ExcludedRoutes;

  List<String>? ipv6Addresses;

  List<int>? ipv6NetworkPrefixLengths;

  List<Ipv6Route>? ipv6IncludedRoutes;

  List<Ipv6Route>? ipv6ExcludedRoutes;

  bool useFd;

  bool log;

  int? tun46Setting;

  bool? defaultNicSupport6;

  Object encode() {
    return <Object?>[
      mtu,
      dnsServers4,
      dnsServers6,
      ipv4Addresses,
      ipv4SubnetMasks,
      ipv4IncludedRoutes,
      ipv4ExcludedRoutes,
      ipv6Addresses,
      ipv6NetworkPrefixLengths,
      ipv6IncludedRoutes,
      ipv6ExcludedRoutes,
      useFd,
      log,
      tun46Setting,
      defaultNicSupport6,
    ];
  }

  static TunnelConfig decode(Object result) {
    result as List<Object?>;
    return TunnelConfig(
      mtu: result[0] as int?,
      dnsServers4: (result[1] as List<Object?>?)?.cast<String>(),
      dnsServers6: (result[2] as List<Object?>?)?.cast<String>(),
      ipv4Addresses: (result[3] as List<Object?>?)?.cast<String>(),
      ipv4SubnetMasks: (result[4] as List<Object?>?)?.cast<String>(),
      ipv4IncludedRoutes: (result[5] as List<Object?>?)?.cast<Ipv4Route>(),
      ipv4ExcludedRoutes: (result[6] as List<Object?>?)?.cast<Ipv4Route>(),
      ipv6Addresses: (result[7] as List<Object?>?)?.cast<String>(),
      ipv6NetworkPrefixLengths: (result[8] as List<Object?>?)?.cast<int>(),
      ipv6IncludedRoutes: (result[9] as List<Object?>?)?.cast<Ipv6Route>(),
      ipv6ExcludedRoutes: (result[10] as List<Object?>?)?.cast<Ipv6Route>(),
      useFd: result[11]! as bool,
      log: result[12]! as bool,
      tun46Setting: result[13] as int?,
      defaultNicSupport6: result[14] as bool?,
    );
  }
}

class Ipv4Route {
  Ipv4Route({
    required this.address,
    required this.subnetMask,
  });

  String address;

  String subnetMask;

  Object encode() {
    return <Object?>[
      address,
      subnetMask,
    ];
  }

  static Ipv4Route decode(Object result) {
    result as List<Object?>;
    return Ipv4Route(
      address: result[0]! as String,
      subnetMask: result[1]! as String,
    );
  }
}

class Ipv6Route {
  Ipv6Route({
    required this.address,
    required this.networkPrefixLength,
  });

  String address;

  int networkPrefixLength;

  Object encode() {
    return <Object?>[
      address,
      networkPrefixLength,
    ];
  }

  static Ipv6Route decode(Object result) {
    result as List<Object?>;
    return Ipv6Route(
      address: result[0]! as String,
      networkPrefixLength: result[1]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TunnelConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is Ipv4Route) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is Ipv6Route) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return TunnelConfig.decode(readValue(buffer)!);
      case 130: 
        return Ipv4Route.decode(readValue(buffer)!);
      case 131: 
        return Ipv6Route.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class XIosApi {
  /// Constructor for [XIosApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  XIosApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<int> getStatus() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_ios.XIosApi.getStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<void> start(Uint8List config, TunnelConfig tunnelConfig) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_ios.XIosApi.start$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config, tunnelConfig]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stop() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_ios.XIosApi.stop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<Uint8List> config() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.tm_ios.XIosApi.config$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Uint8List?)!;
    }
  }
}
